/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktyka;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author makma
 */
public class MainWindowIngredientsCalculator extends javax.swing.JFrame {
    
    /**
     * Creates new form MainWindowIngredientsCalculator
     */
    
    RecipeModelList recipeModelList;
    List<Recipe> recipeList;   
    List<Ingredient> ingredientList;
    public Recipe recipe;
    public Ingredient ingredient;
    
    public MainWindowIngredientsCalculator() {
        initComponents();
        initList();
        fillList();
    }
    
    private void fillList(){
        recipe = new Recipe("Chleb","Ciasto");
        ingredientList = new ArrayList<>();
        ingredient = new Ingredient("maka",500.0);
        ingredientList.add(ingredient);
        ingredient = new Ingredient("woda",300.0);
        ingredientList.add(ingredient);
        ingredient = new Ingredient("sol",20.0);
        ingredientList.add(ingredient);
        ingredient = new Ingredient("drozdze",7.0);
        
        ingredientList.add(ingredient);
        
        recipeModelList.RecipeList.add(recipe);
        
        recipe = new Recipe("bulka","Ciasto");
        ingredientList = new ArrayList<>();
        ingredient = new Ingredient("maka",100.0);
        ingredientList.add(ingredient);
        ingredient = new Ingredient("woda",70.0);
        ingredientList.add(ingredient);
        ingredient = new Ingredient("sol",2.0);
        ingredientList.add(ingredient);
        ingredient = new Ingredient("drozdze",3.0);
        
        ingredientList.add(ingredient);
        
        recipeModelList.RecipeList.add(recipe);
        
        recipe = new Recipe("pizza","danie");
        ingredientList = new ArrayList<>();
        ingredient = new Ingredient("maka",700.0);
        ingredientList.add(ingredient);
        ingredient = new Ingredient("woda",700.0);
        ingredientList.add(ingredient);
        ingredient = new Ingredient("sos pomidorowy",125.0);
        ingredientList.add(ingredient);
        ingredient = new Ingredient("mozarella",250.0);
        
        ingredientList.add(ingredient);
        
        recipeModelList.RecipeList.add(recipe);
    }
    
    private void initList(){
        recipeList = new ArrayList<>();        
        recipeModelList = new RecipeModelList(recipeList);
        jList1.setModel(recipeModelList);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        DeleteButton = new javax.swing.JMenuItem();
        LoadButton = new javax.swing.JMenuItem();
        SaveButton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Standard Recipe Ingredients Amount");

        jButton2.setText("Estimate Ingredients Amount");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu1.setText("Options");

        jMenuItem1.setText("Add");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jMenu1.add(DeleteButton);

        LoadButton.setText("Load");
        LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadButtonActionPerformed(evt);
            }
        });
        jMenu1.add(LoadButton);

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        jMenu1.add(SaveButton);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Exit");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Save and Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        JFileChooser fileChoser = new JFileChooser();
        fileChoser.setDialogType(JFileChooser.SAVE_DIALOG);
        int ret = fileChoser.showSaveDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION){            
            try {
                ObjectOutputStream outputStream;
                outputStream = new ObjectOutputStream(new FileOutputStream(fileChoser.getSelectedFile()));
                outputStream.writeObject(recipeList);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainWindowIngredientsCalculator.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainWindowIngredientsCalculator.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadButtonActionPerformed
        JFileChooser fileChoser = new JFileChooser();
        fileChoser.setDialogType(JFileChooser.OPEN_DIALOG);
        int ret = fileChoser.showOpenDialog(this);
        if(ret == JFileChooser.APPROVE_OPTION){                       
           
            try {
                ObjectInputStream inputStream;
                inputStream = new ObjectInputStream(new FileInputStream(fileChoser.getSelectedFile()));
                recipeList = (List<Recipe>) inputStream.readObject();                
                recipeModelList = new RecipeModelList(recipeList);        
                jList1.setModel(recipeModelList);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainWindowIngredientsCalculator.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(MainWindowIngredientsCalculator.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_LoadButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        List<Recipe> selectedRecipeList = jList1.getSelectedValuesList();
        for(Recipe selectedRecipe:selectedRecipeList){
            recipeModelList.RemoveRecipe(selectedRecipe);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowIngredientsCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindowIngredientsCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DeleteButton;
    private javax.swing.JMenuItem LoadButton;
    private javax.swing.JMenuItem SaveButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<Recipe> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
